version: '3.8'

services:
  betserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: betserver
    environment:
      - PORT=8080
